Param(
    [string]$ArgMes = "Line1`nLine2",
    [INT]$ArgTime = 0,
    [INT]$CloseTime = 120,
    [string]$ArgMesWindow = "Logon script",
    [INT]$ArgButton = 1
)


[void][System.Reflection.Assembly]::Load('PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35')
[xml]$XAML = @'
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="PleaseWaitLogon"       
        WindowStyle="None"
        ResizeMode="NoResize"
        WindowStartupLocation="CenterScreen"
        AllowsTransparency="True"
		Opacity="0.8"
         >

    <Grid>
        <Image HorizontalAlignment="Left" Name="logo" Height="200" Margin="10,46,0,0" VerticalAlignment="Top" Width="200" RenderTransformOrigin="0.5,0.5">
            <Image.RenderTransform>
                <TransformGroup>
                    <ScaleTransform/>
                    <SkewTransform AngleY="-1.172"/>
                    <RotateTransform/>
                    <TranslateTransform Y="-0.716"/>
                </TransformGroup>
            </Image.RenderTransform>
        </Image>

        <Label Content="" Name="Titre" HorizontalAlignment="Center" Margin="244,72,244,0" VerticalAlignment="Top" Width="640" FontSize="60" VerticalContentAlignment="Center" HorizontalContentAlignment="Center"/>
        <Label Content="" Name="Message1" HorizontalAlignment="Center" Margin="0,254,0,0" VerticalAlignment="Top" Width="1200" FontSize="36" HorizontalContentAlignment="Center"/>
        <Label Content="" Name="Message2" HorizontalAlignment="Center" Margin="0,314,0,0" VerticalAlignment="Top" Width="1200" FontSize="36" HorizontalContentAlignment="Center"/>
        <Label Content="" Name="Message3" HorizontalAlignment="Center" Margin="0,374,0,0" VerticalAlignment="Top" Width="1200" FontSize="36" HorizontalContentAlignment="Center"/>


        <Button Name="CloseButton" Content="Close" HorizontalAlignment="Center" VerticalAlignment="Bottom" Margin="0,0,0,80" Width="120" Height="40"
            Background="#FF4C4C" Foreground="White" BorderBrush="Transparent"
            FontSize="16" FontWeight="Bold"
            Cursor="Hand" Visibility="Collapsed">
            <Button.Effect>
                <DropShadowEffect Color="Black" Direction="320" ShadowDepth="3" BlurRadius="5" Opacity="0.5"/>
            </Button.Effect>
            <Button.Template>
                <ControlTemplate TargetType="Button">
                    <Border CornerRadius="20" Background="{TemplateBinding Background}">
                        <ContentPresenter HorizontalAlignment="Center" VerticalAlignment="Center"/>
                    </Border>
                </ControlTemplate>
            </Button.Template>
        </Button>

   </Grid>

</Window>
'@
#Read XAML
$reader=(New-Object System.Xml.XmlNodeReader $xaml) 
try{$Form=[Windows.Markup.XamlReader]::Load($reader)}
catch{Write-Host "Unable to load Windows.Markup.XamlReader. Some possible causes for this problem include: .NET Framework is missing PowerShell must be launched with PowerShell -sta, invalid XAML code was encountered."; exit}

#===========================================================================
# Store Form Objects In PowerShell
#===========================================================================
$xaml.SelectNodes("//*[@Name]") | %{Set-Variable -Name ($_.Name) -Value $Form.FindName($_.Name)}

$CloseRequested = $false


# Calcul de la largeur et de la hauteur désirées comme 95% des dimensions de l'écran
$desiredWidth = [System.Windows.SystemParameters]::PrimaryScreenWidth * 0.50
$desiredHeight = [System.Windows.SystemParameters]::PrimaryScreenHeight * 0.50
# Ajustement de la taille de la fenêtre
$Form.Width = $desiredWidth
$Form.Height = $desiredHeight

# Ajustement de la position de la fenêtre pour la centrer
#$Form.Left = ([System.Windows.SystemParameters]::PrimaryScreenWidth - $Form.Width) / 2
#$Form.Top = ([System.Windows.SystemParameters]::PrimaryScreenHeight - $Form.Height) / 2

$Image_logo = "/9j/4RDYRXhpZgAATU0AKgAAAAgABQEOAAIAAAASAAAIVodpAAQAAAABAAAIaJybAAEAAAAkAAAQiJyfAAEAAAAkAAAQrOocAAcAAAgMAAAASgAAAAAc6gAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEdlYXJzIFZlY3RvciBJY29uAAAB6hwABwAACAwAAAh6AAAAABzqAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHAGUAYQByAHMAIABWAGUAYwB0AG8AcgAgAEkAYwBvAG4AAABHAGUAYQByAHMAIABWAGUAYwB0AG8AcgAgAEkAYwBvAG4AAAD/7QAsUGhvdG9zaG9wIDMuMAA4QklNA+0AAAAAABADhAAAAAEAAQOEAAAAAQAB/9sAQwADAgIDAgIDAwMDBAMDBAUIBQUEBAUKBwcGCAwKDAwLCgsLDQ4SEA0OEQ4LCxAWEBETFBUVFQwPFxgWFBgSFBUU/9sAQwEDBAQFBAUJBQUJFA0LDRQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQU/8AAEQgA8AD4AwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/aAAwDAQACEQMRAD8A/VOiiigAooooAKwPHHj7w38NPDs+veK9csPDujQFVkvtSuFhiVmOFXcx5JPQDk18u/tdf8FKfh9+zUt5oOjtH428fR5jOk2Uw+z2T+tzMMhSD/yzXL9jtyDX40/H39pf4hftL+KTrfjrXZL/AGE/ZdOgzFZWSn+GGEHC+hY5Y4G5jQB/SnBPFdQRzQyJNDIodJI2DKykZBBHUEd6kr8f/wDgmZ/wUM/4QGfTvhH8TNTx4YlYQaDrl2/GmuThbaZj/wAsCeFY/wCrPB+QjZ+wFABVTVtVtNC0u81LULhLSws4XuLi4lOEijRSzMT2AAJ/CrdfFP8AwVk+O3/Cp/2ZLjw1Y3Hla543mOlRhWwy2igNdP7grsiP/XegD8kvjF+094y+IHx88YfEfRfEWs+HbnV79pbZtOvpLaSG2XCW8ZMbDlYlRfqD613/AIB/4KaftE+AfLjXx5J4gtUx/o+v2sV3u+shUS/+P18t0UAfpt4B/wCC3fiaz8qLxr8NtL1QcB7nQ76SzI9/LkEoP03Cv0K/ZT/al8O/tbfDy88W+G9K1TSLay1B9Nnt9VWMP5yxxyEoUdgy4lXk4Oc8V/N/X7a/8EZLUQfsn6vJjBm8VXb59cW9qv8ASgD7zooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK/Lf8A4Kw/tZ/Fz4XeM7b4b+HZh4T8K6rpqXg1rTnYXmoKxZJIvN48kKykFU+YgqS2G21+pFfEf/BWj4Cf8LY/Zsl8V2Ft5uveB5TqSFVy7WTALdJ9AAkp9oT60AfhozF2LMSzE5JPU0lFFABX6p/8E0P+CiyRx6Z8IfipqyxqgW38PeIr6TAAHC2k7n8o3Psh/hr8rKKAP6P/ABr+2j8C/h6ZF1v4p+Go5o/vwWd6t5Kv1jg3sPyr8Z/+CjP7UOm/tQfHr+0fDV5LeeC9Eso7DSZJIni84n55pvLcBlLO23kAlY04FfLFFABRRRQAV+5n/BH61+z/ALHlvJjHn69fSf8Aotf/AGWvwzr9j/8Agkd+0l8Pf+FM6d8J7jWk0vxzbXt1OljfYjW+WSQuPs75w7AYBThuCQCOaAP0Zoorw/47ftpfCD9nWOeLxd4utf7YjGRoem/6VfsewMSf6vPYyFR70Ae4UV+OHx8/4LL+N/Fq3Om/C7QYPBWntlV1bUdt3qDD1VCPKiPtiT2avtj/AIJx/tej9qD4PCy167WT4geGglrqwbAa8jI/dXYA/vgFWx0dWOAGUUAfW9FFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVV1TTLTW9Mu9Ov7eO7sbuF7e4t5RlJY3UqysO4IJB+tWqr6hqFrpNhc317cRWllbRNNPcTuEjijUEszMeAAASSegFAH81v7TPwYu/wBn346+MPAdyHaLSr1hZzSdZrR8SW8mfUxsmcdDkdq8xr6J/bz/AGk7P9qL9oTVPE+k2cdt4fsIV0nS5RFsmubeJnIml7kuzuwB+6pVeoJPztQAUUUUAFFdX8P/AITeNfitqBsfBvhTWPE9ypw6aVZSTiP3cqCFHuxAr37Rv+CX37SmtWwnX4d/Y0IyBe6tZROf+AmbI/EUAfK1FfRfjL/gnh+0T4GtpLi/+F+q3cEYyW0iSHUDj/dgd2/Svn7VNKvdE1Cex1GzuLC+gbZLbXUTRyRt6MrAEH60AVafBPLazxzQyPDNGwdJI2KsrA5BBHQg96ZRQB9B+Iv2/Pj54n8AWHg+8+I+qx6XaxGFp7ZhDeXKdhNcqBK+Bxy3I+9u618/SyvNI8kjtJI5LM7HJYnqSabRQAV6t+zB+0FrX7Mnxl0Pxzo++aO2fyNRsA21b2zcjzYT2yQAyk9HVGwcV5TRQB/UT4C8daL8TfBei+K/Dl6moaJq9ql3aXCfxIwzgjsw5BU8ggg8it+vyO/4I4/tN6rp/iq++CmqRXeoaNfJNqmkTRRtIunyqN0yOQDsikHIJwBJx1lr9caACiiigAooooAKKKKACiiigAooooAKKKKAPj//AIKifHzxD8A/2dLS88I6zNofiXV9at7G3vLbHmxxhXlkIyCMYjCn/fr8qLX/AIKOftIWmNnxT1Jsf89bW1k/9CiNfU3/AAW88ffa/G/w18FRy8WGn3Orzxg9TPIIoyfoLeT/AL6r8yKAPqmz/wCCof7TFnj/AIuP54/6baNp7f8AtCsn4nf8FE/jv8XvAOq+DvEvi+KfQ9URYrxLXTre2kljDBiheNFIU4AIHUZB4JB+bKKACiiigCS3t5bu4iggieaeVgkccalmdicAADkkntX6q/sX/wDBJG1fT7Dxj8coJJJplWe18GxyGMRjqDeOpzu/6ZKRjoxJygzv+CRH7HVrq4/4Xj4tsVuIoJnt/DFrOmUMiHbLe4PBKsDGnoyu2Mqhr9YKAMrwv4U0XwTolto3h7SbLQ9Jtl2w2OnW6QQxj2RQAK1aKKACvLvjj+zL8Nv2i9EfTvHXhe01WTYUg1JF8q9tvQxzr8y4PO3JU9wRXqNFAH4F/tuf8E+vFH7Jt9/bmnzTeJ/h1cyiODWBHiazcn5YrpRwpPQSD5WP90nbXyXX9SfirwtpHjjw3qWga9p8Gq6NqUD213ZXK7o5o2GCpH9eo6jmv55f21P2Y7z9lT45ap4V3S3Ph+6X+0NEvZeTNaOxCqx6F0IZG6ZKhsAMKAPBqKKKACvSfgB+z54y/aU+IVp4R8Gaebq7kxJdXkuVtrGHOGmmfB2qPxLHAUEkCrf7NH7Onib9qL4qWXgnww0FvM8bXd7fXTYjs7VWVZJiM5bBdQFXklgOBkj9/v2bv2a/Bv7L3w8g8LeEbPBbbJqGqTgG51CcDBklYfjtUcKDgdyQDE/ZQ/ZI8G/smeA10Xw9EL7W7tVfVtfnjAuL6QfnsjXJ2xg4GcklizH3GiigAooooAKKKKACiiigAooooAKKKKACiiigD+f3/gpt4+/4T79s7x40cnmWmjtBo0HOdvkxKJB/39MtfLNfsR+07/wR/wBO+JfiTXvGHw/8Z3Gl+INWu5tQutO8Qjz7aaeVy7lZkG+MFmJ5WTr2r83Pjh+x98XP2eZpW8Z+Db610xDhdYs1+02LDsfOjyq59H2t7UAeNUUUUAFafhbw7eeMPE+kaDpyeZqGqXkNjbof4pJXCIPzYVmV7n+w1psOq/tffCSCcBkXxDbTgH+9G3mL+qigD+hD4a+AtM+Fvw/8O+ENGjEemaJYQ2EAxgssaBdx/wBpiCxPckmuloooAKKKKACiiigAr4M/4LE/CCDxt+zZaeNYYAdU8HahHKZgMt9kuGWGVP8Av4bdvbYfWvvOvDv24dOh1T9kL4uQzgMi+HLucA/3o0Mi/wDjyigD+ciiiigD6r/4Jf8AjX/hC/20vAod9ltq4utKm5xnzYH8sf8Af1Y6/f2v5ZdC13UfDGtWOr6RfXGmarYzJcWt7aSmOWCVTlXRhyrAgEEV92/An/gsN8Uvh+LfT/H2n2fxE0lMKbl8WeoKv/XRF2Pgf3kye7UAftbRXzN8Cf8Agor8Efjz9mtLDxQnhnXpsAaN4k22cxY/wo5JjkOegVyfYV9MAhgCDkHoRQAtFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFMmhjuIXilRZYpFKujjKsDwQR3FPooA+Gf24P+CfPwk8UfCLx1438PeFIvDPjLSNKutVhl0I/Z4bl4ozIUkgH7s7grDKqrZPWvw9r+nn4t+LPCvgn4beItW8banb6R4Wis5Ev7q5OFEbqVKgdWZt20KASxIABJr+Yq6SKO5lWCQywq5CSMu0sueDjtkUAR16R+zZ43h+G37QXw58T3Ugis9L1+yuLlycBYRMvmn/vgtXm9FAH9U/Wlr5j/wCCeH7R1v8AtFfs4aFcXN0JvFPh6NNH1qJmzIZY1AjnPciWMK2em7zAPumvpygAooooAKKKKACvmL/gpR44h8C/sY/ESWSQJcapbxaRboTzI08qIwH0j8xvopr6dr8f/wDgsr+0db+K/Gmg/CLRroTWfh1v7S1kxtlTeumIoj7xxMxPvPjqpoA/NeiiigAooooAK/Wv/gipq3jLxDpnxCk1XxJqt94U0pbSy07S7u5aW3hmfzHkMatnZhUjGFwPn6V+Slful/wSK8A/8If+yBYaq8eyfxLq15qZJHOxWFsg+n+jkj/e96APtaivPPjX+0B4C/Z68LNr3jzxFbaJaEEQQMd9xdOB9yGJcs56dBgZySBzX5E/tYf8FXfHfxnF54e+Hi3Hw/8AB8m6N7iOQf2peIePnlU4hU/3YznqC7A4oA/bmivzr/4Jjft+r8VNLsfhP8Q9Rz40sYvL0bVbl+dWgQf6p2PWdFHXq6jJ+ZWLfopQBy/xP+Iuj/CP4eeIfGfiCVotH0Sykvbgpje4UZCICQC7HCqMjJYCvm/4bf8ABU39nv4hiKO48U3PhG9kx/o3iKyeAA+8qb4h+LivAv8AgtD+0B/Y3hHw18IdMucXWsONY1hUbkW0bEW8bezyqz+xgX1r8jKAP6ivCPj7wz4/08X3hjxFpXiKyIz9o0q9juU/76RiK3q/l8+GtzqVv490CPSb+7029uL6C3S4sp3hlG+RV4ZSCOvav6g6ACiiigAooooAK434ufF7wr8DPAepeMPGWqx6TotivzO3LzOc7Yol6vI2MBR7ngAkdNrF7NpmkX15b2U2pT28Dyx2duVEk7KpIjQsQu5iMDJAyeSK/nc/a+/aw8cftS/EWe+8ULLo2labLJBpvhlSwj04ZwwYEAtMcfO5AJIwAoAUAGr+2b+2v4r/AGufGXmXJl0bwTp8pOk+HkkyqdR50xHDzEd+iglV6sW+caKKACiiigD2z9kf9qXxD+yd8V7XxVpCtf6TcKLbWNHaTal9bZyRn+GRT8yPjg8cqzA/0AfBX44eDf2gfAtn4s8E6vFqmmXAAkjyFntZcZaGaPOUcZ5B68EEggn+ZOu++DPx38dfs/eK18Q+A/EN1oV+QFmSIhobpAc7Jomysi+zDjqMHmgD+mqivy9+DH/Ba/Sbi0t7P4p+CbmzvAAsmq+GWEsLn+8beVgyfg7/AEr6T0X/AIKk/s16vbiSTx/Jpr4yYb3R71WH4rCw/ImgD6vor4z8Y/8ABWz9nfwzbSvp+u6v4pnUHEGk6TMhY+m6cRL+tfFv7Qv/AAWJ8ffECzutH+G2jx/D/TJQUOqSyC51J1/2DgJDn2DMOoYUAfbv7ef7fmg/sueGbnw/4eubbV/ihfQ4tbBSJE01WHFxcDtgHKxnljgkbcmvwk1rWb/xHrF9q2qXc1/qV9O9zdXdw5eSaV2LO7MeSSSST70zUtSvNZ1C5v8AULqe+vrmRpZ7m5kMksrscszMxJYk8kmq1ABRRX0x+wR+yTd/tXfGSCyvopY/A+iFLzXrtMrujydlsrDo8pUjrkKHYcqAQD5nor+hK5/4Jufs23ed/wALbBf+uV9eR/8AoMwrFvP+CWn7NN2SR8PpID/0x1q/H/tc0AfgP1r+mP8AZz8BD4XfAX4feFDH5c2laHaW864xmYRKZT+Llj+NeCwf8Eo/2dbTULa7t/DGpQyQSrKq/wBsXDqSpBAIZjkcdK+v6APxO/4LGfCjUPB/7RuneMWnubnRvFenKYDPIzrb3FuFjlhQEnau0xSYHGZW4r4Ir98f+CoHwPHxl/ZT1+7tIPN1vwmw1+zKj5jHEpFwmeuDC0jY7tGtfgdQBZ0zU7vRdStNQ0+6msr+0lSe3ubdykkMikMrqw5VgQCCOQRX6O+Hv+C2HjHSPAekabffD7Tta8UW1uIrvW59QaKK6ccCT7OkfykjBYB8ZzgKCAPzZooA9A+PXxs8QftEfFXXPHvibyU1TVHT/R7UMIbeNECJHGGJIUKo78nJPJNef0UUAei/s4aWdb/aG+GGnhS/2rxRpkJUdw11GDX9Mdfyw6Vqt7oWp2mpabdz6fqFpKs9vd2shjlhkUgq6MMFWBAII5BFfol8L/8Ags/408J/DFtI8VeEbXxh4ttgsVnrjXX2VJkx965jVDucccoV3Z5wRlgD9jKytG8V6J4iutQttJ1iw1O506UQXsNndJM9tIRkJIFJKNjnDYNfz7/HD/goF8bvj19ottZ8Xz6Lok2QdF8PZsrYqf4WKnfIPaR2rU/4J7ftVSfsu/HW0udTuWTwV4g2adrseTtjQt+6ucesTMSep2NIByRQB/QTRTIZo7iFJYnWWJ1DI6HKsDyCD3FFAD6/Hr/grp+yH/whPixfjP4Xstuh67OIdfhhX5ba+b7txgdFmxhj/wA9BknMgFfsLXPfEHwFonxR8E634S8R2S6hoesWr2l3bt3RhjKn+FgcMrDkEAjkUAfy8UV6n+03+z/rf7M3xk1zwLrW6ZbV/OsL4rtW9s3J8qZfqAQwGcMrrnisj4TfAj4gfHPWP7M8CeE9S8SXCsFke0h/cQ5/56zNhIx7swoA4Oiv1K+An/BFm6uBb6l8XvFYtE4c6D4bId/92S5dcD0IRG9nr239oD/gkd8LPHngi2t/hvB/wgPifT4fLt7lppbi2vMZO25DszZJP+sXkZ5DABQAfiRRXdfGj4I+Mv2fvHNz4T8caPJo+rxKJYwWDxXEJYhZonHDoSrYI7gg4IIHC0AFFFFABRRRQAUUUUAFfs5/wRg+Iug618B/Efg61srax8RaHqpur14hiS9hnH7qZz3ZTG8fHAVE7mvxjr6W/wCCd/x6/wCFAftReGNRvLn7P4f1tv7D1YscIsM7KEkb0CSiJyf7qsO9AH9CVFFFAHyB+19/wUb8O/sj/EnSvB9/4TvfE11eaaupTTWd4kP2dWkdFUqynJPlseo4I9a8r0z/AILZfCqbaL/wP4wtc9TbrazAfnMtfnr/AMFC/iP/AMLP/bC+I+oxy+baWF//AGPb4OVC2qiBsexdHb/gVfOlAH6N/t3/APBULS/jx8MYfAvwvtta0bTdUJOvXuqRJBNJCCNttGEkf5WPLnIyAF5DMK/OSiigC/oHh/U/FetWWj6Lp91q2q3sohtrKyhaWaZz0VEUEk+wr9A/gl/wRl8f+MtPttS+IfiWy8CQygONMtoft96Bjo+GWND9GfHcCvsb/gnB+xHpv7Onw5sPF/iPTkl+JmvWyzXEs6ZfS4HGVtY8/dbBBkI5LfLyFGftCgD83bj/AIIjfD1rHbB8RfE0d5j/AFslvbvHn/cCg/8Aj1fMv7QH/BIr4qfCnTbrWPB17bfEnSIAXeCwga31FVHcW5LCT6RuzH+7X7eUUAfytTwSW00kM0bRTRsUeN1KsrA4IIPQimV+vf8AwVc/Yk03xB4T1H41+DNOS08QaYBL4jtLZMLfW3Q3WB/y0j4Ln+JMknKc/kJQAUUV+o3/AAT/AP8Agl2dVTTviP8AGjS2SzO240rwhdJgy91lvFPRehEJ5P8AHxlSAfUn/BLbxj4/8V/ssaND440e6tLbTG+yaDql2cPqGngDym2n5tqfcViAGVUxnBJK+u4YY7eJIokWOJFCqiDCqBwAB2FFAD6KKKAPKvjL+y78Mv2gda8O6p4+8LweILrQTIbPzZHRSr4ykgQjzEyoIVsjOeOTn0Lw54Z0jwfo9vpOhaVZaLpduu2Gy0+3SCGMeiooAH4CtOigAooooA/Ev/gs7dmf9q7RYs5EHhS0THpm5um/rXwXX27/AMFg7r7R+2FLHnPkaBYx/rI3/s1fEVABRRQBk4FAHtH7P/7HvxV/abt7678BeHV1DTLCYW91qFzdxW0EUhAbbl2BY4IJCg4BGeor6VP/AARj+McHhHUtTn1/ww+r29u01to1pPNJJcuBnyvMaNERjyAckZxkgcj9MP2GfgV/wz1+zN4Q8MXFv5Gtzwf2pq4Iw32ycB3VveNdkWfSIV73QB/LDq2k3ug6peabqVpNYajZzPb3NrcxmOWGRSVZHU8hgQQQemKq1+1v/BSH/gnvF8d9MuviP8PrFIviLZQ5vbCEBRrcKjgf9fCgYU/xgBT0XH4rXNtLZ3EsE8TwTxMUkikUqyMDggg8gg9qAI6KnsbG51S9gs7O3lu7u4dYobeBC8kjk4Cqo5JJ4AFfpJ+yH/wSI1jxb9i8UfGtp/D+jtiSLwrbPtvrgdR9okH+pU90H7zqCYyKAPvP9gP49/8ADQ37MfhbXLq5+0a/pif2NrBZssbqBVG9j6yRmOQ+8hHavoS9+0fY5/snl/avLbyvOzs34+XdjnGcZxWP4I8CeHfht4as/D3hbRrLQdFs12QWVjCI419TgdSepY5JPJJNb1AH87f7SP7Fvxp+BOqalrHjTw3PqWmzTPPN4k0km7snZmJZ3cDdHkk/6xUNfPdf1TOiyoyOodGGCrDII9DX59/8FIP2IPhbJ8B/GvxK8N+FLfw74z0eGO987R/9HguV86MS+bCvyE+W0jbgA2QCSRxQB+Lte4fsRfD21+KP7WHwx8PX0Sz2MurpdXELjKyx26tcMjD0YRFT7GvD6+iP+Cevi228F/tm/CzULuQRwS6m2n7m4G65hkt0/wDHpVoA/ogooooAKKKKAKWtaPZ+ItGv9K1G3S60++t5LW5gkGVkidSrqfYgkfjX8wnxC8Kt4F8f+JvDbuZH0fU7nTi56sYpWjz/AOO1/ULLKkETySOscaAszscBQOpJr+Yb4u+J4fG/xX8aeIrbm31fW73UIv8AdlneQfo1AHJ1/Sx+zd8YdB+NXwf8K69o+u2Gs3cml2jajHaXKyyWtyYVMkcqg5Rw24ENg8V/NPW94K8e+JPhvr0Gt+Fdd1Dw7q0P3LzTbl4JAPQlSMg9weD3oA/qKor8lP2PP+Cr3xG8Q+OvCvw+8eaBbeNZdav7fTLfWLHbaXsbyuqB5VA8uQDOTgIcZJJooA/WuiiigAooooAKKKKAPxB/4KyfD3xheftWa/4iTwtrT+Gzp9jFDq62ErWj7YF3AShdvDEgjPBFfCtf1T9a818e/sz/AAn+KAkPin4d+G9Znk+9dTadELj8JVAcfg1AH80VfTH/AATr+BP/AAvn9qbwtYXdv5+g6G39u6oGGVMUDKURh0IeUxIR/dZvSv0z8ff8EgvgH4t82TRrfXvBs7cr/ZWomaIH3W4Ehx7AivRP2L/2HdC/Y3t/FhsNdm8TX+vTxE31zaLA8NvGp2Q4DNn5ndiwxn5ePloA+maKKKACvgD9ur/gmJD+0J40sfG3w7udO8NeJb65WPXorvcltdIet2AgJEw/iGMSdchgS/3/AEUAfNX7KP7BPw3/AGVbKK9061/4SLxmybZ/E2pRgzDI5WBORAnXhcsQcMzV9K0UUAFFFFABX5af8FIP+CkWkXGieIfg98NHtdb+3Qyafr3iEgS28cbArJb23Z3IyGk6L0XLfMvoH/BX/wCLXxV+HHw30HTfCkn9leBdfaSx1nV7JmF2ZsEras3/ACzjkQMcry+xlJA4f8YqACprG+uNMvbe8tJntrq3kWWGaJtrRupyrA9iCAc1DRQB/RP+xR+1VpH7Vvwb0/XI54YvFenolpr+mqQGguQP9YF/55y4LoenVc5Rq+ga/mQ+DXxt8ZfAHxva+K/BGszaPq0PyPt+aK5iJBaKaM8OhwOD3AIwQCP1T+Cf/BZ/wH4g0+3tPid4dv8Awnq4AEt/pMZvLFz3bbnzY/8Adw/+9QB+jlFfK9x/wVA/ZpgsPtQ+I6y8ZEMej35kPtjyK+Zf2gP+C0WkwabdaZ8H/DVzdag4KLr3iGMRww/7UdurFnPcbyoBHKsOKAPav+CoH7XFh8C/g3f+CNHvkbx54utXtIoYmy9lZPlJrh8cqWXdGnQliWGdhr8L63PG/jnX/iT4q1HxL4o1a61zXdQkMtzfXb7pJG6D2AAAAUYAAAAAAFYdABRX3B+zP/wSq8bftDfCaz8dXXiW08G22pOW02zvrJ5pLm3HAnJDDYrHO3g7gN3QgnttS/4Il/FGLd/Z/jvwjden2j7VDn8onoA8z/4JM/Dj/hO/2wdH1KWLzLTwxp91q8mR8u/aII/xDzqw/wByiv0E/wCCb/7D3ij9kdvHV/40u9Hv9X1o2tvaSaRPJKkcEfmM+S8aEFmdeMfwCigD7aooooAKKKKACiiigAooooAKKKKACiiigAooprusaM7sFVRksTgAUAOor4n+Nn/BV/4SfCf4i6Z4W0sXHjWJbsQazq2kyA2unx9GaNsH7Q6nBKp8uM/Pu4r7E8L+KNJ8a+HdO17QdQt9V0bUYFubS9tXDxzRsMhlNAGpRX52/wDBXz9pvWfhV4T8HeBfCGu3ug+I9XuTq13eaXdPb3ENpCSsa70IYCSUk8H/AJYEd6+D/AX/AAU2/aJ8BeWi+O38QWqY/wBH160iu931kKiT/wAfoA/cn43fCDQvjz8LPEXgXxFHu03WLYw+aqgvbyj5opk/2kcKw7ZXB4Jr+b74t/C/XPgt8SfEHgnxJb/Z9Y0W6a2mAztkHVJEz1R0Kup7qwr+jv4AeOdT+J3wO8A+L9Zjt4dW13Q7PUrqO0QpEsksKuwRWJIXLcAk/Wuc+JH7Inwk+L/xJsfHXjLwbZeIdfs7RbONrws0DorFl8yEHZIRuYAuDwcdhgA/n6+E37PvxG+OmpfYvAng/VPEbBtslxbQkW8R/wCmkzYjT/gTCvS/2g/2BPjB+zZ4WsPEfijRre90S4QG5vdFmN1Hp7k4EdwQo2Hp8wyhJADZ4r+hDSNHsNA0230/S7G202wt12Q2tpEsUUa+iooAA9gKqeL5beDwlrct5DFc2iWM7TQzoHjkQRsWVlPBBGQQeCKAP5bqKCckn1ooAKK7T4R/Bnxn8d/Fy+GPAmhTeINbMD3JtoZEjCRKQGdndlVVBZRkkcsB1New/Fz/AIJ3fG74I/DW58ceKPDltHpFpIq3cdjex3U9qjf8tZFjyAgOAWBONwzxk0AfNVSW832e4il2JJ5bBtki7lbBzgjuKjooA/pp+APxH0n4u/BXwX4w0SCCz03VdLhmSztgBHasF2yQKBwPLdWjwP7ld/X5m/8ABFn45jWPBXiz4Uahcg3ejzf2zpcbt8xtpSFnVR/dSXY31uDX6ZUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABXxb/wVl8N+MtV/ZWvdU8Ka3qGn2OlXaS65p1lIUW+sX/dsHx8zBHMbFc7du8sDgY+vtS8VaLo12trf6xYWN0yCRYbm5SNypJAIUkHGQefauH+N/wAQ/h5oPwa8Zaj401OyufCC6XPFqUMcyO08MiFDEgB5d92xR3LCgD+aOvqD9lL/AIKEfEb9k/w7qvh7RoLHxHoF0fOtdN1kyNHYzk/M8WxlIVhncmcE4YYO7d8x3Pkm5l+zhxb7z5YlILBc8ZxxnFb3gL4c+KPij4hh0LwjoGoeI9XlGVs9Nt2mcL3Y4HyqO7HAHc0AdN+0H8fvFX7S3xLvPG/i97UapcQxWyW9jG0dvbxRrhUjVmYgZLMcsclmPevN6+s4P+CWH7Sk+li8/wCEEgjYruFrJrNkJj+Hm4B9ia+e/ib8IPGvwZ17+xvG/hnUvDOokFki1CAoJVHVo3+7IvupIoA/fr9jn4seB/EP7KngO80nxTpdxY+H/D1hYarK1wsYsJ4rZFkScNjyyGU8tgEcjIINeYfFf/grD8DPhx4is9H0zUbzxrI11HDeXuhxbrS0iLAPJ5rYEpVckCIMGxjcK/CqO7nht5oI5pEgm2mSJXIV8cjcOhxnjNRUAf1O6Tq1nr2lWep6ddRX2n3sKXNtdQOHjmidQyOrDggggg+hrjP2gdUGh/Ab4kaiWCC08NalPuJxjbayN/SviL/gjb8cPFnjT4b694A1nTL680DwwyvpWvupMMayHLWLOerKTvQDOFZgdoCA/olqOnWmsafc2N/aw3tjcxtDPbXMYkjljYYZGU5DKQSCDwQaAP5YKK/oI+JH/BNT9nr4k+bJL4Dg8O3j5xdeHJnsSv0jU+V+aGvl3x5/wRC0ie7WXwX8S7yztjIN1prtgk7BM84liKcgdPk59RQB2n/BHH9n/wD4Qj4Pat8TtTttmreLpvs9gXX5o7CFiMjuPMlDk+ojjNfoPfWNtqllcWd5bxXdncRtDNbzoHjlRhhlZTwQQSCDwQazvB/hTTPAnhPRvDei24tNI0izisbSAfwRRoEQe/AHNbFAH4Vf8FF/2ELr9mbxa/i3wlay3Hwx1ic+TjLnSJ25+zSHr5Z58tz2+U8gFuc/ZS/4JxfEz9pl7PWLi3bwZ4FlIc69qcJ3XCf9O0PDS/7xKp1+YkYr96dc0DTPE+lT6ZrOnWmrabPjzbO+gWaGTDBhuRgQcEAjI6gGrqIsaKqqFVRgKBgAUAeKfs1/se/DX9lnRTb+D9HD6xNEI7zxBf4lvrocEgvgBEJAOxAq8AkE817bRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAfgT/wAFSfHn/Cc/tneMY45PNtdDitdHhOc48uJWkH4SySivk2v1e/au/wCCRHiXxv418T+Ovh94zh1bUdav7jU7nRvEC+S/myyNIyxToCpGWIVWVcADLGvzR+K3wg8YfBDxfN4Y8caFceHtbjjE32a4KsHjJIV0dSVdSVYBlJHB9KAKPw58Bat8UvHvh/whoUIn1jW72KxtlY4UO7BdzHsozknsATX9Fn7NH7NHg/8AZd+HFn4X8L2cZuSitqWrvGBc6jPj5pJD1xnO1M4UcDuT+M//AASrt7K4/bd8D/bApeO31B7YP3lFnNjHvt3H8K/fKgArg/jV8EvCH7QHgK/8I+NNKi1LTLpT5cmAJ7SXGFmhfGUkXsR15BBBIPeUUAfzM/tA/BjVv2fPjD4n8A6y4nutHuvLjuVXatzAwDwzAdt8bK2MnBJHauw/Yw/Zytv2pfjxpXge+1oaFpzQyX13Mi7ppYYsF4oQRjzGB4LcABjhsbT9Bf8ABZ23sof2rNFe22i5l8LWrXW3u/2i5Ck++wL+AFfH3wd+L3if4EfETSvG3g+9Sx17TS/kySwrLGVdGjdWRhggqzD1GcgggGgD+k34afDPw18H/BWmeEvCOkwaLoOnR+XBawD8WdmPLuxyWZiSSSSa6ivzG+An/BaLStbls9J+Kng6fS72Vli/tjw0DPA7HgFrZj5ijP8AdaQ88Cv04ByAaAFooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAIL6+ttLsri8vLiK0s7eNppridwkcSKMszMeAAASSeABX4Lf8FMP2kvB/wC0p8ebXUfBkEk2maFp/wDZH9sOcDUdsrvvRMZCAyMFJ5bOcAYr9Df+CuHhL4ja/wDs4f2h4O1e4i8M6ZOZvE+j2qYe7tTt2Slh8xjiYZaPoQ28/wCrr8OqAOy+DfxQ1T4K/FPwv450cB9Q0K+jvEiZtqzKDh4mI6K6FkPsxr+j34K/Gfwt8ffh1pXjPwhqCX2lX8YLJkebay4G+CVf4ZEJwR9CMggn+ZCvRPgt+0L8Qv2etffV/APie80C4lwLiCMiS3uQOglhcFH74JGRk4IoA/pkrnfiD8QfD3wr8Hap4p8VapBo2habCZrm7uGwFA6ADqzE4CqMliQACTX44W//AAWf+OEOlfZn0PwXPdAY+2vp9yH+pUXAXP4Y9q+Yfjx+1R8Tv2k9QiuPHvie41S1t3L22mQqsFnbnGMpCgC7scbjlsd6AG/tTfHe7/aS+Ovijx7cQvaW2oTiOxtJDk29pGoSFDjjdtUFscbmY968oor98P2Rf2Pfgfa/s2eBZf8AhD/DXjt9T02LUp9e1fSILie6lmUO/Mikoqk7AmflCYPzZJAPx1/Yz8B/8LL/AGqPhfoDR+bBNrlvczx4+9DAfPlH/fETV/SFXmvg/wDZq+FHw+8SW3iDwx8OPDHh/XLYOINQ0zSoYJow6lG2sqgjKsQfYmvSqACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAgv7C21SxuLK8t4ruzuY2hmgmQOkiMMMrKeCCCQQeua/PPw1/wAEYPh1bfEjWtY1/wAS6nqHhOS9ebTPDlkPIMUJORFNcEs7hclflCkhQd2Sa/ROigD55+IH7EfwO1X4M3/g8/D3SdN0a1hkuYJtOhEN5BKqHEq3HMhfgZLltwGGBHFfzu1/Uh4xsrrUvCOuWliglvbixnigQsFDSNGwUZPA5I5r+d7x7+xF8d/ht5ra38LvEIgjzuuNPtvt0Kj1LwF1A+poA8w8AeAde+KPjPSfCnhfTn1bX9VnFvaWcbKpkfBP3mIVQACSSQAASTXsPx7/AGFPi9+zb4N07xT4z0KCPR7qbyJZtPuluhZyHGxZynC7uQpBIJGMgkA/V3/BGj9n+4vviX4s+JutWEtunh2H+yNPW4iKkXky5mYZ5DJDhSPS4r9ZfFHhfSfG3h3UdB17T7fVtG1GBra7srpA8c0bDBUj/OKAP5a6/Zn/AIIyfFvVvFPwU8Q+B9StLx7PwxfeZpuoPE3kGGfLvbh8Y3JIHfGc4mHYVleD/wDgjB4P074y6rq+v+JLjVPhzHOJtL8PwlkupFPJiuZ+MIp+UFPmcYJKHg/ob4S8IaJ4D8PWWg+HNKtNE0ayjEdvY2MKxRRL7KOPcnqTyaANeiiigAooooAKKKKACiiigAooooAKKKKAP//Z"
$bitmap_Logo = New-Object System.Windows.Media.Imaging.BitmapImage
$bitmap_Logo.BeginInit()
$bitmap_Logo.StreamSource = [System.IO.MemoryStream][System.Convert]::FromBase64String($Image_logo)
$bitmap_Logo.EndInit()
$bitmap_Logo.Freeze()

$logo.source 		= $bitmap_Logo
$Form.Title 		= $ArgMesWindow
$Titre.Content 	    = $ArgMesWindow

$Messages = $ArgMes.Split("`n")
if ($Messages.Count -gt 0) { $Message1.Content = $Messages[0] }
if ($Messages.Count -gt 1) { $Message2.Content = $Messages[1] }
if ($Messages.Count -gt 2) { $Message3.Content = $Messages[2] }

# Configuration du DispatcherTimer
$timer = New-Object System.Windows.Threading.DispatcherTimer
$timer.Interval = [TimeSpan]::FromSeconds($ArgTime)
$timer.Add_Tick({
    $Form.Close()
    $timer.Stop()
})

if ($ArgTime -ne 0) {
    $timer.Start()
}

# fenêtre reste en avant-plan
$Form.Topmost = $true


# Affichez temporairement la fenêtre pour calculer la position centrée
$Form.WindowStartupLocation = "CenterScreen"
$Form.Show()
$Form.Hide()

# Capturez la position centrée comme position initiale
$initialLeft = $Form.Left
$initialTop = $Form.Top

# Réinitialisez WindowStartupLocation si nécessaire
$Form.WindowStartupLocation = "Manual"

# Gérez l'événement LocationChanged pour réinitialiser la position
$Form.Add_LocationChanged({
    $Form.Left = $initialLeft
    $Form.Top = $initialTop
})

$CloseButton.Add_Click({
    $CloseRequested = $true
    $Form.Close()
})

# Création d'un DispatcherTimer
$showButtonTimer = New-Object System.Windows.Threading.DispatcherTimer
$showButtonTimer.Interval = [TimeSpan]::FromSeconds($CloseTime)

$showButtonTimer.Add_Tick({
    $Form.Dispatcher.Invoke([Action]{
        $CloseButton.Visibility = 'Visible'
    })
    $showButtonTimer.Stop()
})
# Démarrer le timer
$showButtonTimer.Start()

$CloseButton.Add_Click({
    $Form.Close()
})

$Form.Add_Closing({
    param($sender, $e)

    if (-not $CloseRequested) {
        $e.Cancel = $true
    }
})

# Affichez la fenêtre modale
$Form.ShowDialog()